version: "3.7"
services:
  nginx:
    build: requirements/nginx
    ports:
      - 80:80
    volumes:
      - WordPress:/var/www/html/
    restart: always
    depends_on:
      - wordpress

  mariadb:
    build: requirements/mariadb
    volumes:
      - DB:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    restart: always

  wordpress:
    build: requirements/wordpress
    volumes:
      - WordPress:/var/www/html/
    depends_on:
      - mariadb
    ports:
      - 9000:9000
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      WP_URL: ${WP_URL}
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
    restart: always

# networks:
#
volumes:
  WordPress:
    driver: local
    driver_opts:
      type: none
      device: /Users/hyunsoo/dajeon/wp

      o: bind
  DB:
    driver: local
    driver_opts:
      type: none
      device: /Users/hyunsoo/dajeon/db
      o: bind
